Script started on 2015年03月11日 (週三) 09時26分56秒
]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ whoami;pwd
F74036051
/home/F74036051/lab1
]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git config -l
user.name=f74036051
user.email=f74036051@ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/f74036051/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git init
Reinitialized existing Git repository in /home/F74036051/lab1/.git/
]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github[K]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github[K]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github.com[K]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github.com/f74036051/github.git[K]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github.com/f74036051/github.git[K]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github.com/f74036051/github.git[K]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ git clone https://github.com/f74036051/github.git[1P.git[1P.git[1P.git[1P.git[1P.git[1P.gitl.gita.gitb.git1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74036051@2015cpp: ~/lab1F74036051@2015cpp:~/lab1$ exit

Script done on 2015年03月11日 (週三) 09時31分37秒
